### ISSUE TITLE
reduce memory usage in single thread mode

### ISSUE THREAD

**Issue by phuongdao1** [npgall/concurrent-trees#14]
First thank you for the implementation. It is very capable of handling large data sets in efficient running time. I tried concurrent suffix tree to store around 4 million string and each length around 50 using only single thread. However, it consumes around 50gb of memory. Are there anyway to modify the code to make the package use less memory ?

**Comment by npgall** [comment]
Hi, this is not a bug. Please use the discussion forum as requested on the site.
