### ISSUE TITLE
Consider optimizing NodeUtil#binarySearchForEdge()

### ISSUE THREAD

**Issue by panghy** [npgall/concurrent-trees#26]
The way that it's implemented right now isn't very GC friendly. It seems like it would be trivial to actually implement binary search directly.

**Comment by npgall** [comment]
This sounds reasonable. I will try to look into this for the next release. I'm hoping to get time for this in the next few weeks.

**Comment by panghy** [comment]
Cool, thanks!

**Comment by npgall** [comment]
Merged. Many thanks for the PR!

This will be included in the next release.
