### ISSUE TITLE
API for retrieving keys/values

### ISSUE THREAD

**Issue by anantharaman93** [npgall/concurrent-trees#32]
Hi.

It would be nice to have to have a API to get keys and values in the tree. Similar to Map.keySet() and Map.values()

These APIs would be helpful for iteration and traversing.

Thanks.

**Comment by npgall** [comment]
You can use `tree.getKeyValuePairsForKeysStartingWith("");`.

It will return all of the keys and values in the tree. There are similar methods for just accessing the keys, or just accessing the values.

Hope that helps,
Niall

**Comment by anantharaman93** [comment]
Hi. Thanks for the immediate help.
